app:
  resource: '@AppBundle/Controller/'
  type: annotation

test:
  resource: "@TestBundle/Resources/config/routing.yml"
  prefix:   /bundle_yml

test_2:
  resource: "@TestBundle/Resources/config/routing2.yml"
  prefix:   /bundle_yml2

logout:
  path: /users/logout
