test_annotations_category:
    resource: "@TestAnnotationsBundle/Controller/CategoryController.php"
    type:     annotation

app:
  resource: '@AppBundle/Controller/'
  type: annotation

test:
  resource: "@TestBundle/Resources/config/routing.yml"
  prefix:   /test

test_2:
  resource: "@TestBundle/Resources/config/routing2.yml"
  prefix:   /test2

test_annotations:
  resource: "@TestAnnotationsBundle/Controller/"
  type:     annotation
  prefix:   /
