# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  encoders:
    AppBundle\Entity\User: bcrypt
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    chain_provider:
      chain:
        providers: [in_memory, mysql]
    in_memory:
      memory:
        users:
          ryan: #pass = 'ryanpass'
            password: $2a$12$LCY0MefVIEc3TYPHV9SNnuzOfyr2p/AXIGoQJEDs4am4JwhNz/jli
            roles: 'ROLE_USER'
          admin: #pass = 'kitten'
            password: $2a$12$cyTWeE9kpq1PjqKFiWUZFuCRPwVyAZwm4XzMZ1qPUFl7/flCM3V0G
            roles: 'ROLE_ADMIN, ROLE_USER'
    mysql:
      entity:
        class: AppBundle:User
        property: username

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    users:
      pattern: ^/users
      anonymous: ~
      provider: chain_provider
      form_login:
        login_path: /users/login
        check_path: /users/login
      logout:
        path:   /users/logout
        target: /users
      logout_on_user_change: true

    main:
      anonymous: ~
      logout_on_user_change: true
      # activate different ways to authenticate

      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
      #http_basic: ~

      # https://symfony.com/doc/current/security/form_login_setup.html
      #form_login: ~

  access_control:
    # require ROLE_ADMIN for /users/admin*
    - {path: ^/users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - {path: ^/users/admin, roles: ROLE_ADMIN }
